os:
  - linux
  - osx

language: c

env:
  - BRANCH=1.0.6
  - BRANCH=1.2.0

cache:
  directories:
    - "$HOME/.nimble/bin"
    - "$HOME/.choosenim"

install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=$HOME/.nimble/bin:$PATH
  - |
    if ! type -P choosenim &> /dev/null; then
      export CHOOSENIM_CHOOSE_VERSION=$BRANCH
      curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
      sh init.sh -y
    fi

script:
  - nimble -y test

before_deploy:
  - nimble docs

deploy:
  provider: pages
  edge: true
  cleanup: false
  strategy: git
  keep_history: true
  token: $GITHUB_TOKEN
  target_branch: gh-pages
  local_dir: docs
  on:
    branch: devel
    condition:
      - "$(uname -s) = Darwin"
      - "$BRANCH = 1.2.0"
